### ISSUE TITLE
takeUntilFound gets overwritten

### ISSUE THREAD

**Issue by stephenscholz** [cartant/eslint-plugin-rxjs-angular#3]
https://github.com/cartant/eslint-plugin-rxjs-angular/blob/fba9a040eb345bce3a7545c37db14ed9688ae4fd/source/rules/prefer-takeuntil.ts#L267

the boolean "takeUntilFound" gets overwritten if "takeUntil" is not the last operator in the pipeline.

Replacing `takeUntilFound = found;` with `takeUntilFound = takeUntilFound || found;` should solve the problem

**Comment by cartant** [comment]
Fixed in 1.0.2.
