### ISSUE TITLE
prefer-takeuntil alias not working with take(1) only with take(var)

### ISSUE THREAD

**Issue by Abasz** [cartant/eslint-plugin-rxjs-angular#5]
When using `take` as an alias for `takeUntil` with a number the rule incorrectly shows an error:

```typescript
   onSubmit(): void {
        this.manageSettings
            .saveSetting(this.settingsForm.value)
            .pipe(take(1))
            .subscribe({
                next: (): void => {
                    this.discardChanges();
                },
                error: (errors: IValidationErrors): void => {
                    parseErrors(this.torrentSettingsForm, errors);
                },
            });
    }
```

However it work correctly if a variable is used with a number literal:

```typescript
   onSubmit(): void {
        const s = 1;
        this.manageSettings
            .saveSetting(this.settingsForm.value)
            .pipe(take(s))
            .subscribe({
                next: (): void => {
                    this.discardChanges();
                },
                error: (errors: IValidationErrors): void => {
                    parseErrors(this.torrentSettingsForm, errors);
                },
            });
    }
```

Please fined below the related ESlint rule:
```json
"rxjs-angular/prefer-takeuntil": [
                    "warn",
                    {
                        "alias": ["untilDestroyed", "take"],
                        "checkComplete": true,
                        "checkDestroy": true
                    }
                ]
```

**Comment by cartant** [comment]
`take` is not an alias for `takeUntil`. The rule's purpose is to ensure that a subject is use to notify subscriptions of component destruction and `take` has no way of doing that. And if the source to which the subscription is made does not emit a notification, you'll have a memory leak.

**Comment by Abasz** [comment]
Thanks for the prompt reply. 

You have a point (of which I have not thought of) where the original observable never emits and `take(1)` would not fire (and complete the observable stream). In such case you are right further unsubscription handling would be necessary. 

I wanted to use this with simple one-off http calls to prevent the warning showing up but probably in that case ignore comment would be a way better approach without the unnecessary overhead of adding an operator.

**Comment by khaled4vokalz** [comment]
> 

@cartant ,
don't you think it should take into consideration the operators which unsubscribe internally e.g. take, first etc.? This would've helped this package for more generalized usage....
