### ISSUE TITLE
rror while loading rule 'rxjs-angular/prefer-takeuntil': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.

### ISSUE THREAD

**Issue by Youhy** [cartant/eslint-plugin-rxjs-angular#6]
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/5111924/110622907-267d4000-81ad-11eb-82b6-ad7698820386.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/5111924/110623025-4d3b7680-81ad-11eb-8c85-3cd2137d1ea0.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/5111924/110623050-53c9ee00-81ad-11eb-9739-af66eaea0215.png">

**Comment by cartant** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md
